# Generated by Django 3.1.7 on 2021-03-15 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0002_auto_20210315_0831'),
    ]

    operations = [
        migrations.CreateModel(
            name='Andamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servico', models.IntegerField()),
                ('status', models.IntegerField()),
            ],
        ),
    ]
