# Generated by Django 3.1.7 on 2021-03-17 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0004_clienteservico'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicos',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='servicos',
            name='pago',
            field=models.BooleanField(default=0),
        ),
    ]
